### ISSUE TITLE
incompatibility with gzip plugin

### ISSUE THREAD

**Issue by bastianlb** [dschmidt/ember-cli-deploy-sentry#8] opened 2016-01-21 23:29 UTC
sentry doesn't support gzipped source maps, so when used in combination with the gzip plugin, the source maps/js files aren't useful. Is there a way to make this plugin send the source files before they get gzipped?

**Comment by bastianlb** [comment] 2016-01-22 00:40
i've tried adding `before: ember-cli-deploy-gzip` in `package.json` as described in the documentation, although this doesn't seem to work.. Sentry still reports a bad encoding. However, disabling the gzip plugin for `.js` and `.map` files fixes this..

**Comment by dschmidt** [comment] 2016-01-22 00:50
This is odd, I have zero issues with the gzip plugin used alongside ember-cli-deploy-sentry.

Will need to investigate...

**Comment by dschmidt** [comment] 2016-01-22 00:50
What exactly is the issue you're seeing? Any errors I can try to reproduce?

**Comment by bastianlb** [comment] 2016-01-22 01:00
Sure, when `getsentry.com` gets an event with source files it can't parse they report a `utf-8` error:

```
There were 2 errors encountered while processing this event
Source file was not 'utf8' encoding: https://asdfasdf123.cloudfront.net/assets/vendor-30820b336a9f.js Expand
Source file was not 'utf8' encoding: https://asdfasdf123.cloudfront.net/assets/client-30820b336a9f.js Expand
```

**Comment by bastianlb** [comment] 2016-01-22 01:05
Up until recently, sentry swallowed these errors silently.. see here: https://github.com/getsentry/sentry/commit/3124ce50f7537a7bd7bb3556667e20207b8ab23a

**Comment by dschmidt** [comment] 2016-01-22 01:06
Interesting, wondering why it works for me then

**Comment by dschmidt** [comment] 2016-01-22 01:09
Although this should work of course .. here's a workaround that might work for you:

use the keep option of ember-cli-deploy-gzip and configure your webserver to serve .gz files if present (c.f. https://www.npmjs.com/package/ember-cli-deploy-gzip#keep)

for nginx the config option is gzip_static: http://nginx.org/en/docs/http/ngx_http_gzip_static_module.html

**Comment by dschmidt** [comment] 2016-05-25 08:26
Does this issue remain? Or is it maybe fixed with the juggling around of hooks?

**Comment by dschmidt** [comment] 2016-06-23 20:26
Closing, due to inactivity

**Closed as completed by dschmidt** 2016-06-23 20:26 UTC
